version: '3'
services:
  caddy:
    image: caddy/caddy:latest
    volumes:
      - /srv/data:/srv/caddy
      - static_volume:/staticfiles
      - media_volume:/media

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  web:
    image: helfertool/helfertool:latest
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
      - /etc/helfertool/helfertool.yaml:/config/helfertool.yaml
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

volumes:
  static_volume:
  media_volume:
  postgres_data:
  rabbitmq_data:
